### ISSUE TITLE
Sparam File Incompatible for branch s4p

### ISSUE THREAD

**Issue by zamyers** [StanfordVLSI/dragonphy2#118]
The file "Case4_FM_13SI_20_T_D13_L6.s4p" under data is not parseable by the s4p_to_impulse function call. The rest of the s4p files under data are.

**Comment by sgherbst** [comment]
Thanks for catching this -- I'll take a look.

**Comment by sgherbst** [comment]
This turned out to be caused by a few non-ASCII characters in the comments section of that S4P file.  I fixed those issues in the latest commit to the `s4p` branch.
