### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by mahorowitz** [StanfordVLSI/dragonphy2#25]
## 11/22
- Make multibit error correct happen properly
- How Fault handles analog signals
- 	Have the adaptation running on the Phy
-	Have the new mProbo working to characterize a cell
-	Make the emulation useable for software development (might push this)
-	ACORE
-	System Model
	- Add bad channel model
	- Phase interpolator with correct fixed codes

## 12/6
-	Have complete templates for the selected type of cells
-	System Model:
	- Use stochastic ADC
	- Add the CDR implementation

## 12/13  
- System Model:
	- Memory and test hardware
	- JTAG

## 12/20
- Have a demo for DaVE, and complete Dragon Phy, and emulation Dragon Phy

### 11/8 -  
-	Take back-end blocks and push to master  - To be done today!
	-	No adaptation, forward path with MLSD 
-	How to link software into our system, to make emulation better (olivia)
        - Not as pressing an issue, since first tests won't need it
	   -	For tests that do need it, there are two options
			- Emulated time on the software.  Or not
			 - We will chose not, and just read the data when the processor is ready
-	Extracting parameters from simulation data (daniel) Done
-	Create a list of circuit templates that you want to create by Jan  Done
	- Phase blender
	- V2T
	- Sample and hold
	- Bias gen
-	Create a plan for moving design over to real design Done
		○ Low-loss channel model
		○ Connect digital back end
		○ Add bad channel model
		○ Phase interpolator with correct fixed codes
		○ Swap out ADC for one with real TI hierarchy
		○ Use stochastic ADC
		○ Add the CDR implementation
		○ Memory and test hardware
		○ JTAG

**Comment by sgherbst** [comment]
Closing this as it referred to a previous tapeout effort.
