### ISSUE TITLE
Investigate ADC sampling order

### ISSUE THREAD

**Issue by sgherbst** [StanfordVLSI/dragonphy2#3]
Order seems to be 0, 5, 10, 15, 1, 6, 11, 12, etc. instead of 0, 4, 8, 12, 1, 5, 9, 13, etc. as I would expect.  It looks like this is due to the way that the sampling sequence is initialized.  I could be mistaken, because there are several places where the data are reordered, but when I re-order the data this way I get reasonable-seeming results.

**Comment by sjkim85** [comment]
I will also check the synthesized net. I could be real problem since the "V2T_clock_gen"  is the block that has the biggest change than before.

**Comment by sgherbst** [comment]
This was resolved awhile ago.
