### ISSUE TITLE
Where does JTAG fit into the reset sequence?

### ISSUE THREAD

**Issue by sgherbst** [StanfordVLSI/dragonphy2#60]
During a meeting a few days ago, we defined the reset sequence as:
1. De-assert ``ext_rstb``
2. De-assert ``int_rstb`` (over JTAG)
3. Assert ``en_inbuf``
4. Assert ``en_gf``
5. Assert ``en_v2t``

But I realized this doesn't include the JTAG reset pin, ``phy_trst_n``.  Where does that belong in this sequence?

**Comment by zamyers** [comment]
the JTAG reset pin is controlled by the JTAG controller.

-Zach

On May 1, 2020, at 9:42 AM, Steven Herbst <notifications@github.com> wrote:

﻿

During a meeting a few days ago, we defined the reset sequence as:

  1.  De-assert ext_rstb
  2.  De-assert int_rstb (over JTAG)
  3.  Assert en_inbuf
  4.  Assert en_gf
  5.  Assert en_v2t
But I realized this doesn't include the JTAG reset pin, phy_trst_n. Where does that belong in this sequence?

**Comment by sgherbst** [comment]
Sorry, to clarify I mean *when* this should happen, rather than *how*.  It definitely needs to happen before step 2 (since that involves JTAG communication), so I think my question can be simplified to "which should be de-asserted first, ``ext_rstb`` or ``phy_trst_n``"

**Comment by zamyers** [comment]
It happens after ext_rstb is de-asserted. I can double check the logic but I believe the ext_rstb acts as a standard reset inside the JTAG and the JTAG's trst_n's primary function is to reset JTAG state machine into a known state.

-Zach
________________________________

**Comment by sgherbst** [comment]
Great, thanks.  In that case I'll update the reset sequence to
1. De-assert ``ext_rstb``
2. De-assert ``phy_trst_n``
3. De-assert ``int_rstb`` (over JTAG)
4. Assert ``en_inbuf``
5. Assert ``en_gf``
6. Assert ``en_v2t``
