### ISSUE TITLE
Add method to directly set PI codes

### ISSUE THREAD

**Issue by sgherbst** [StanfordVLSI/dragonphy2#62]
Using ``en_ext_max_sel_mux=1``, ``ext_max_sel_mux=31``, ``ext_pi_ctl_offset=0 -> 511``, the highest value we can set for the PI is ``495``, and PI codes are occasionally repeated as ``ext_pi_ctl_offset`` is swept upwards.  Also, we need to make remember to set ``en_ext_pi_ctl`` to ``1`` and ``ext_pi_ctl`` to ``0``.

To simplify things and allow us to direcly control the PI, I suggest we add a bypass for directly setting the PI code.

Numerical example: with ``ext_max_sel_mux=31``, ``ext_pi_ctl_offset=511``,  ``pi_ctl_cdr=0`` (by setting the two CDR registers I mentioned above)
```shell
scale_value = ext_max_sel_mux << 4 = 31 << 4 = 496 
unscaled_pi_ctl = pi_ctl_cdr + ext_pi_ctl_offset = 0 + 511 = 511
scaled_pi_ctl = unscaled_pi_ctl * scale_value = 511 * 496 = 253456
int_pi_ctl_cdr = scaled_pi_ctl >> 9 = 253456 >> 9 = 495
```

**Comment by zamyers** [comment]
Implemented in the test_dev branch and will be closed upon PR.
