### ISSUE TITLE
Ext_max_mux_sel creates non-mononicity

### ISSUE THREAD

**Issue by zamyers** [StanfordVLSI/dragonphy2#8]
When I enable the external max mux sel, the PI test reports that there is non-monotonic behavior. It seems this behavior always occurs at one point and to me, it looks like a linearity issue. 

You can reproduce this by enabling the external max mux select in the ffe_dev branch. 

-Zach

**Comment by sjkim85** [comment]
It makes sense to me. My opinion is like this.
If value of the external max_mux_sel is not correct (which means that it is different from the internal max_mux_sel value), period estimation of input clock is incorrect and it eventually leads to phase wrapping in wrong position. So it can cause a discontinuity in the position.

**Comment by sgherbst** [comment]
Closing as related to #59
